[settings]
# Enable Lockfile: https://mise.jdx.dev/dev-tools/mise-lock.html .
lockfile = true

[tools]
caddy = "latest"
cosign = "latest"
"npm:@devcontainers/cli" = "latest"
"ubi:railwayapp/railpack" = "latest"
